version: '3.8'
services:

   postgres-db:
     image: postgres
     restart: always
     environment:
       POSTGRES_USER:
       POSTGRES_DB:
       POSTGRES_PASSWORD:
     volumes:
       - ./postgres:/var/lib/postgresql/data
     ports:
       - 5432:5432